# Stage 1: Build the React app
FROM node:14 as build-stage

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app files to the working directory
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Serve the built React app using a lightweight web server
FROM nginx:alpine as production-stage

# Copy the built app from the previous stage to the nginx directory
COPY --from=build-stage /app/build /usr/share/nginx/html

# Expose port 80 to allow access to the React app
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]
